### PR TITLE
Tag configuration files as examples

### PR DESCRIPTION
**Pull request by aaperis**
The filepaths of the conf files can be changed easily via the added `.env` file. I also renamed `docker-compose.yml` itself since it held much of the configuration.

### CODE REVIEW

**Review by jbygdell — APPROVED** [review]

**Review by pahatz — APPROVED** [review]
Looks good!

**Comment by andkaha** [comment]
@aaperis @jbygdell This has the same issue as the PR in the other starter-kit PR (https://github.com/GenomicDataInfrastructure/starter-kit-htsget/pull/7):  The example configuration files should not need to be touched by the user. Instead, the user should copy these to create the actual configuration (which is then untracked by Git).  The compose file should not refer to the example configuration but to the configuration files the user creates using the example files as template.

**Comment by aaperis** [comment]
@kusalananda  The idea here is that the user does not need to do anything except `docker compose -f docker-compose-example.yml up` to have a running stack locally.
If the user wants to modify files, he/she can copy the example compose and modify it, same with the configuration files.

Template files for production-like deployment already exist here:
https://github.com/GenomicDataInfrastructure/starter-kit-se-deployment-notes/tree/main/storage-and-interfaces .

I agree that this has become maybe less clear but I think that's what we decided (basically being able to pull updates from this repo without messing the user's production configuration).

**Comment by andkaha** [comment]
> @kusalananda The idea here is that the user does not need to do anything except `docker compose -f docker-compose-example.yml up` to have a running stack locally. If the user wants to modify files, he/she can copy the example compose and modify it, same with the configuration files.
> 
> Template files for production-like deployment already exist here: https://github.com/GenomicDataInfrastructure/starter-kit-se-deployment-notes/tree/main/storage-and-interfaces .
> 
> I agree that this has become maybe less clear but I think that's what we decided (basically being able to pull updates from this repo without messing the user's production configuration).

But the README suggest running the service with the example configuration, which means the user will edit the files that are checked out from the repository.  This means those edits will be blocking the user from updating their repository.

The ordinary way to do things like this is to 

1. Provide examples of configuration files, either in a separate `examples` directory, or in files with an extra `.examples` filename suffix.
2. The user deploying the service will make copies of these files and modify them to their needs.  The original example files are untouched.
3. The service will expect to find real user-supplied configuration files, created with the examples as template.

By just changing the configuration files' names to include the word `example` and then using them with that name in the service, you have gained nothing.

**Comment by aaperis** [comment]
>  But the README suggest running the service with the example configuration, which means the user will edit the files that are checked out from the repository.

To avoid possible misunderstandings, the user does not need to edit any files, only run  `docker compose -f docker-compose-example.yml up` and this will deploy the example working system locally. This is what is suggested in the README, as far as I am aware.

We could add some explanatory text about copying the files and how to change the paths in the included `.env` file for people who wish to edit the files but I expected that this is common sense. We can resolve this on Monday :-)

**Comment by andkaha** [comment]
To make it more convenient for the user, one could have a short shell script called `setup` that simply copies the example files to the non-example names/locations (and that refuses to do so if the files are already in place).

**Pull request merged**
