### PR TITLE
Rename config files to examples

### PR DESCRIPTION
**Pull request by aaperis**
This PR reorganizes a bit the configuration structure of the stack:

- config files are renames with `.example` extension
- all env variables are moved away from the docker-compose file and into the `.env` which is also now named `.env.example`

I think this allows for a cleaner way for the user to tailor configurations at their own needs while not affecting the ease of deploying the example stacks we have in the repo. Thanks @kusalananda,  @nanjiangshu and @viklund for the nice suggestions.

### CODE REVIEW

**Review by nanjiangshu — COMMENTED** [review]
Looks great @aaperis! There is just one thing left, there are still changes for the file [scripts/sda-admin](https://github.com/GenomicDataInfrastructure/starter-kit-storage-and-interfaces/blob/rename-config-files-to-examples/scripts/sda-admin) on the GDI server that are not updated here.

**Comment by aaperis** [comment]
Yes I noticed that `scripts/sda-admin`  has changes but I am not sure if this is because the repo in the VM is not up to date. I'll look into that.

Edit: There is a branch [cert-script-cleanup](https://github.com/GenomicDataInfrastructure/starter-kit-storage-and-interfaces/tree/todo/cert-script-cleanup) which has most of the changes in the `scripts/sda-admin` that the file in the VM has. I believe it would be best if that branch is updated and a PR is opened to resolve this. I created the related issue #33.

**Review by andkaha — APPROVED** [review]
Approved after discussion with Alex.

**Comment by andkaha** [comment]
> Looks great @aaperis! There is just one thing left, there are still changes for the file [scripts/sda-admin](https://github.com/GenomicDataInfrastructure/starter-kit-storage-and-interfaces/blob/rename-config-files-to-examples/scripts/sda-admin) on the GDI server that are not updated here.

We have now looked at that script to clarify what the changes are, and there are no changes to that script that I think would have an impact on anything.

**Review by nanjiangshu — APPROVED** [review]

**Pull request merged**
